export default [
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
  {
    title: "Mom’s Discharge Plan",
    subTitle: "Karen Becker",
    description: "Sed mollis mi iaculis tincidu...",
    date: "Oct 12",
    unreadCount: 2,
  },
];
